# Site settings
title: 'Justin Peterson' # Your Title
tagline: 'Tech Lead @ HubSpot' 
sidebar_image: /images/cover.jpg
261-image: /images/python-logo.png 

# Build settings
baseurl: "" 

permalink: pretty
